config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :guest_books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest_book.rb
class GuestBook < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guest_books_controller.rb
class GuestBooksController < ApplicationController
  before_action :set_guest_book, only: [:show, :edit, :update, :destroy]

  # GET /guest_books
  # GET /guest_books.json
  def index
    @guest_books = GuestBook.all
  end

  # GET /guest_books/1
  # GET /guest_books/1.json
  def show
  end

  # GET /guest_books/new
  def new
    @guest_book = GuestBook.new
  end

  # GET /guest_books/1/edit
  def edit
  end

  # POST /guest_books
  # POST /guest_books.json
  def create
    @guest_book = GuestBook.new(guest_book_params)

    respond_to do |format|
      if @guest_book.save
        format.html { redirect_to @guest_book, notice: 'Guest book was successfully created.' }
        format.json { render :show, status: :created, location: @guest_book }
      else
        format.html { render :new }
        format.json { render json: @guest_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guest_books/1
  # PATCH/PUT /guest_books/1.json
  def update
    respond_to do |format|
      if @guest_book.update(guest_book_params)
        format.html { redirect_to @guest_book, notice: 'Guest book was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest_book }
      else
        format.html { render :edit }
        format.json { render json: @guest_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guest_books/1
  # DELETE /guest_books/1.json
  def destroy
    @guest_book.destroy
    respond_to do |format|
      format.html { redirect_to guest_books_url, notice: 'Guest book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest_book
      @guest_book = GuestBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_book_params
      params.require(:guest_book).permit(:user_id, :title, :message)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_books_helper.rb
module GuestBooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/guest_books/_form.html.erb
<%= form_for(guest_book) do |f| %>
  <% if guest_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest_book.errors.count, "error") %> prohibited this guest_book from being saved:</h2>

      <ul>
      <% guest_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guest_books/edit.html.erb
<h1>Editing Guest Book</h1>

<%= render 'form', guest_book: @guest_book %>

<%= link_to 'Show', @guest_book %> |
<%= link_to 'Back', guest_books_path %>

app/views/guest_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guest Books</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guest_books.each do |guest_book| %>
      <tr>
        <td><%= guest_book.user_id %></td>
        <td><%= guest_book.title %></td>
        <td><%= guest_book.message %></td>
        <td><%= link_to 'Show', guest_book %></td>
        <td><%= link_to 'Edit', edit_guest_book_path(guest_book) %></td>
        <td><%= link_to 'Destroy', guest_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest Book', new_guest_book_path %>

app/views/guest_books/new.html.erb
<h1>New Guest Book</h1>

<%= render 'form', guest_book: @guest_book %>

<%= link_to 'Back', guest_books_path %>

app/views/guest_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @guest_book.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @guest_book.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @guest_book.message %>
</p>

<%= link_to 'Edit', edit_guest_book_path(@guest_book) %> |
<%= link_to 'Back', guest_books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArroyoWagner2017</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>